version: '3.8'

services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server-title-detection
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    command: ["serve"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  app:
    build: .
    depends_on:
      - ollama-server
    environment:
      - OLLAMA_HOST=ollama-server-title-detection
      - OLLAMA_PORT=11434
    volumes:
      - .:/app

volumes:
  ollama:
